classes:
- system.linux.system.repo.mcp.salt
- system.linux.system.repo.ubuntu
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- system.reclass.storage.system.physical_control_cluster
- system.reclass.storage.system.opencontrail_analytics_cluster
- system.reclass.storage.system.opencontrail_control_cluster
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_proxy_cluster
- system.reclass.storage.system.openstack_database_cluster
- system.reclass.storage.system.openstack_message_queue_cluster
- system.reclass.storage.system.openstack_telemetry_cluster
- system.reclass.storage.system.stacklight_log_cluster
- system.reclass.storage.system.stacklight_monitor_cluster
- system.reclass.storage.system.stacklight_telemetry_cluster
- system.reclass.storage.system.cicd_control_cluster
- cluster.mcpk8s.infra
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/tlichten/mcpk8s"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$Qr0XdRvdciun2ucl$osj7gvaoxoOsV9BSiZLD0cqYysOCxA/i8CYTgSpCTnqGF25n8.m/QgP5xrOxE46RtJkY4Ta1AaGODHuiA/iwt1"
    salt_master_host: ${_param:infra_config_address}
  reclass:
    linux:
      system:
        kernel:
          sysctl:
            net.bridge.bridge-nf-call-iptables: 0
    storage:
      node:
        infra_kvm_node01:
          params:
            keepalived_vip_priority: 100
            linux_system_codename: xenial
        infra_kvm_node02:
          params:
            keepalived_vip_priority: 101
            linux_system_codename: xenial
        infra_kvm_node03:
          params:
            keepalived_vip_priority: 102
            linux_system_codename: xenial
        openstack_control_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
        openstack_database_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
        stacklight_log_node01:
          classes:
          - system.elasticsearch.client.single
        stacklight_monitor_node01:
          classes:
          - system.grafana.client.single
          - system.kibana.client.single
        openstack_telemetry_node01:
          params:
            linux_system_codename: xenial
            keepalived_vip_priority: 100
        openstack_telemetry_node02:
          params:
            linux_system_codename: xenial
            keepalived_vip_priority: 101
        openstack_telemetry_node03:
          params:
            linux_system_codename: xenial
            keepalived_vip_priority: 102
        stacklight_log_node01:
          classes:
          - system.elasticsearch.client.single
        stacklight_monitor_node01:
          classes:
          - system.grafana.client.single
          - system.kibana.client.single
        openstack_control_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
        openstack_database_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
        openstack_compute_rack01:
          name: ${_param:openstack_compute_rack01_hostname}<<count>>
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          repeat:
            count: 100
            start: 1
            digits: 3
            params:
              single_address:
                value: ${_param:openstack_compute_rack01_sigle_subnet}.<<count>>
                start: 101
              tenant_address:
                value: ${_param:openstack_compute_rack01_tenant_subnet}.<<count>>
                start: 101
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
